data:
    name: 'coco'
    cache_in_memory: false
    validation_size: 100
model:
    name: 'magic_point'
    batch_size: 50
    learning_rate: 0.001
    detection_threshold: 0.001 # 0.015
    nms: 4
    top_k: 1000
    homography_adaptation:
        num: 100
        aggregation: 'sum'
        filter_counts: 0
        homographies:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.1
            perspective_amplitude_x: 0.1
            perspective_amplitude_y: 0.1
            allow_artifacts: true
            patch_ratio: 0.5
eval_iter: -1
